apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-service
  template:
    metadata:
      labels:
        app: flask-service
    spec:
      containers:
      - name: flask-container
        image: kalkilinux/flask-service:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP

