name: Deploy with Helm to EKS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-north-1
  CLUSTER_NAME: eks-test
  ECR_REGISTRY: 087016008394.dkr.ecr.eu-north-1.amazonaws.com

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up dynamic image tag
        run: |
          echo "IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push product_service image
        run: |
          docker build -t $ECR_REGISTRY/python-ns/repo:$IMAGE_TAG ./product_service
          docker push $ECR_REGISTRY/python-ns/repo:$IMAGE_TAG

      - name: Build and push user_service image
        run: |
          docker build -t $ECR_REGISTRY/node-js/repo:$IMAGE_TAG ./user_service
          docker push $ECR_REGISTRY/node-js/repo:$IMAGE_TAG

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/v1.29.1/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/kubectl
          
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $CLUSTER_NAME

      - name: Verify access to cluster
        run: kubectl get no
